### ISSUE TITLE
Rancher must be ran with the --privileged flag

### ISSUE THREAD

**Issue by ryoryotaro** [rancher/quickstart#129]
Hi,all.

I used the Vagrant Quick Start with virtualbox.

After `vagrant up` command following logs appeared endlessly.

```
    server-01: + docker run --rm --net=host appropriate/curl -sLk https://127.0.0.1/ping
    server-01: + sleep 5
    server-01: + true
```

I logged in the server-01 and looked rancher container log with `docker logs` command.

```
ERROR: Rancher must be ran with the --privileged flag when running outside of Kubernetes
```

So, I changed [configure_rancher_server.sh](https://github.com/rancher/quickstart/blob/0f2b728d1288fda80c2cf92ce74ed9560fda26a3/vagrant/scripts/configure_rancher_server.sh#L17) to use privileged mode.

```
docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged -v /opt/rancher:/var/li    b/rancher rancher/rancher:${rancher_version}

```

It worked fine !

Has privileged mod been need to run in v2.5.x ?

**Comment by inductor** [comment]
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/#privileged-access-for-rancher-v2-5

**Comment by nikkelma** [comment]
You're correct, the Vagrant quickstart was pulling in the `latest` tag instead of `stable` and therefore required the `--privileged` flag, the above merged PR moves the Vagrant quickstart to `stable` instead which allows running the Vagrant quickstart without any further modifications. Will close only after feedback, can even leave this open if we want to move this focus to the changes needed to support 2.5.

**Comment by Dean-Coakley** [comment]
@nikkelma This can be closed as it was done in: https://github.com/rancher/quickstart/pull/143 ?
