### ISSUE TITLE
Node status is stuck on Unknown

### ISSUE THREAD

**Issue by nlitterat** [rancher/quickstart#34]
Trying to run the quick start vagrant version the machines are created and there is no error in scripts
accessing the Admin UI on https://172.22.101.101 works and show me the cluster
However, the node never get connected to the K8S cluster
and is stuck on status unknown

getting the following error in UI
This cluster is currently Provisioning; areas that interact directly with it will not be available until the API is ready.

[[network] Host [10.0.2.15] is not able to connect to the following ports: [nc: unrecognized option: address, BusyBox v1.27.2 (2018-06-06 09:08:44 UTC) multi-call binary., , Usage: nc [OPTIONS] HOST PORT - connect, nc [OPTIONS] -l -p PORT [HOST] [PORT] - listen, , -e PROG	Run PROG after connect (must be last), -l	Listen mode, for inbound connects, -lk	With -e, provides persistent server, -p PORT	Local port, -s ADDR	Local address, -w SEC	Timeout for connects and final net reads, -i SEC	Delay interval for lines sent, -n	Don't do DNS resolution, -u	UDP mode, -v	Verbose, -o FILE	Hex dump traffic, -z	Zero-I/O mode (scanning), --address:2379]. Please check network policies and firewall rules]

Side note: can not access the machine which the master is running on tried to copy ssh public key but with little success

**Comment by gshimansky** [comment]
I just encountered the same error and googled this github issue. I want to leave a comment here so that someone else who googles the same error will know how to fix it.

For me the problem was that in script `configure_rancher_node.sh` variable `agent_ip` was empty because my VMs are configured differently and there is no `eth1` interface. I fixed name of the interface in this script and node launched successfully.
